### ISSUE TITLE
any support for typescript for this 

### ISSUE THREAD

**Issue by jnachman123** [shinenic/react-krpano-hooks#3]
Looks great, trying to use it however no types for typescript, is this something that will be added in the future? thanks again

**Comment by shinenic** [comment]
Hi @jnachman123,

sorry for the inconvenience,
actually, I am planning to have a code refactoring with typescript this year but I can't give you an explicit date,
I will update the latest news once I start the refactoring.

Thanks.

**Comment by jnachman123** [comment]
thank you

**Comment by shinenic** [comment]
Hi @jnachman123 ,
I know it has been a while,
but I just release the latest version that supports typescript,
feel free to upgrade it and leave comments if any issues

**Comment by jnachman123** [comment]
Hi @shinenic , will take a look, thank you
