### ISSUE TITLE
useKrpano is always large size regardless of div or embedpano sizes

### ISSUE THREAD

**Issue by jnachman123** [shinenic/react-krpano-hooks#4]
i am unable to get the size down regardless , does the width and height actually work? thanks

**Comment by shinenic** [comment]
Hi @jnachman123 
I am glad you solved the problem probably,
is there anything else I can help with this issue?

**Comment by jnachman123** [comment]
@shinenic 
Closed too soon - Well actually it still is a issue, no matter what I do I have no control over the size, if I wanted a small viewer I cannot get it to be small.
it seems to take up all space regardless of size settings in embedpano of in the div  , no way i can shrink this , is there any settings hardcoded on size - do not have this issue in JS implmentation?

**Comment by jnachman123** [comment]
have you been able to implement this with e.g. a 300 x 300 pixels for example, im struggling - i believe its a bug

**Comment by shinenic** [comment]
Have you tried the optional arguments `height` and `width` in the doc?

**Comment by jnachman123** [comment]
Yes, no difference in afraid

**Comment by shinenic** [comment]
Hi @jnachman123 
Could you provide your code in `code sandbox`, `Github`, or `Github gist` so I can reproduce it?
I have tested `300px x 300px` on my example and it works fine.

**Comment by jnachman123** [comment]
Can you send me your example please , might be someone wrong on my end

**Comment by shinenic** [comment]
Please check the `file changes` in the [example pull request](https://github.com/shinenic/react-krpano-hooks/pull/5/files)

**Comment by shinenic** [comment]
btw, you can pull down my source code and run the demo page to test it via the following shell scripts.
```shell
git clone https://github.com/shinenic/react-krpano-hooks.git

cd react-krpano-hooks/example

npm install

npm start
```

Thanks.

**Comment by jnachman123** [comment]
thank you , having seen your code example i realised i am putting height and width in the embed params , so that explains it.

thank you very much for your help. look forward to the next update.
